"""FiLM-LSTM: LSTM with Feature-wise Linear Modulation of gate pre-activations by static attributes.

Reference: Perez et al. 2018, "FiLM: Visual Reasoning with a General Conditioning Layer" (AAAI).
This is a hydrology-specific adaptation: static catchment attributes modulate all 4 LSTM gate
pre-activations via affine (gamma, beta) parameters generated by a small MLP.
"""
from typing import Dict, Tuple

import torch
import torch.nn as nn

from neuralhydrology.modelzoo.basemodel import BaseModel
from neuralhydrology.modelzoo.inputlayer import InputLayer
from neuralhydrology.modelzoo.head import get_head
from neuralhydrology.utils.config import Config


class _FiLMGenerator(nn.Module):
    """MLP that maps static attributes to per-gate (gamma, beta) FiLM parameters.

    Output: (gamma, beta) each of shape [B, 4 * hidden_size], one pair per LSTM gate (i, f, g, o).

    bounded=True (film_site='preact'): gamma = 1 + tanh(raw), bounded to (0, 2). Needed there because
    gamma multiplies the full pre-activation INCLUDING the recurrent term h @ weight_hh, so unbounded
    gamma amplifies the recurrence until BPTT gradients exploded and clip_grad_norm turned inf into
    NaN -> crash. Caveat: Perez et al. 2018 (Sec. 4.2) show range-restricting gamma costs about as
    much as removing gamma conditioning entirely, and that negative gamma matters (36% of their
    learned gammas are negative) — the bound is a stability hack that cripples FiLM.

    bounded=False (film_site='input'): gamma = 1 + raw, unbounded and sign-free as in the original
    paper. Safe because in 'input' mode gamma only scales the input projection x @ weight_ih, never
    the recurrent term, so it does not enter the recurrent Jacobian and cannot compound over time.

    Identity initialization: final-layer weights AND biases are zero, so raw≡0 -> gamma=1, beta=0
    at init in both modes (the LSTM behaves as a vanilla LSTM regardless of static input).
    """

    def __init__(self, cfg, static_size: int, bounded: bool = True):
        super().__init__()
        self._bounded = bounded
        H = cfg.hidden_size
        mid = cfg.film_generator_hidden_size

        self.mlp_gamma = nn.Sequential(
            nn.Linear(static_size, mid),
            nn.ReLU(),
            nn.Linear(mid, 4 * H),
        )
        self.mlp_beta = nn.Sequential(
            nn.Linear(static_size, mid),
            nn.ReLU(),
            nn.Linear(mid, 4 * H),
        )
        self._identity_init()

    def _identity_init(self):
        # gamma = 1 + tanh(raw): final weight=0, bias=0 -> raw≡0 -> gamma ≡ 1 at init (no-op)
        nn.init.zeros_(self.mlp_gamma[-1].weight)
        nn.init.zeros_(self.mlp_gamma[-1].bias)
        # beta: final weight=0, bias=0 -> beta ≡ 0 at init
        nn.init.zeros_(self.mlp_beta[-1].weight)
        nn.init.zeros_(self.mlp_beta[-1].bias)

    def forward(self, s: torch.Tensor) -> Tuple[torch.Tensor, torch.Tensor]:
        raw = self.mlp_gamma(s)
        if self._bounded:
            # (0, 2) bound: required in 'preact' mode where gamma multiplies the recurrent term
            # (unbounded there -> BPTT explosion -> clip_grad_norm inf->NaN, see class docstring).
            gamma = 1.0 + torch.tanh(raw)
        else:
            # 'input' mode: gamma never touches the recurrence, so it stays unbounded and can be
            # negative / >2 as in Perez et al. 2018.
            gamma = 1.0 + raw
        return gamma, self.mlp_beta(s)


class FiLMLSTM(BaseModel):
    """LSTM with FiLM-modulated gate pre-activations by static attributes.

    Differences vs. EA-LSTM:
      - EA-LSTM: input gate uses static-only path `sigma(W_s * s + b_s)`, kept constant over time.
        Other 3 gates (f, o, g) are dynamic.
      - FiLMLSTM: all 4 gates (i, f, g, o) are dynamic. Static attributes generate per-gate
        (gamma, beta) vectors that affinely modulate pre-activations before sigmoid/tanh.

    cfg.film_site selects WHERE the modulation applies:
      - 'preact' (legacy default): gamma * (x@W_ih + h@W_hh + b) + beta. Because gamma multiplies
        the recurrent term, it must be bounded to (0, 2) for stability — which Perez et al. 2018
        show costs about as much as no gamma conditioning at all (and audits show the bound binds).
      - 'input': gamma * (x@W_ih) + beta + h@W_hh + b. gamma only scales the input projection and
        never enters the recurrent Jacobian, so it is UNBOUNDED (negative / >2 allowed) as in the
        original paper. Equivalent to a per-basin diagonal row-rescaling hypernetwork on W_ih.

    Identity initialization (gamma=1, beta=0) makes the model behave as a vanilla LSTM at init.
    """
    module_parts = ['embedding_net', 'film_generator', 'head']

    def __init__(self, cfg: Config):
        super().__init__(cfg=cfg)
        self._hidden_size = cfg.hidden_size
        self.embedding_net = InputLayer(cfg)

        if self.embedding_net.statics_output_size == 0:
            raise ValueError('FiLMLSTM requires static inputs.')

        self._film_site = cfg.film_site
        self.film_generator = _FiLMGenerator(cfg,
                                             static_size=self.embedding_net.statics_output_size,
                                             bounded=(self._film_site == 'preact'))

        # 4-gate LSTM parameters: order is (i, f, g, o) along the 4H axis
        input_size = self.embedding_net.dynamics_output_size
        H = cfg.hidden_size
        self.weight_ih = nn.Parameter(torch.empty(input_size, 4 * H))
        self.weight_hh = nn.Parameter(torch.empty(H, 4 * H))
        self.bias = nn.Parameter(torch.empty(4 * H))
        self._reset_parameters()

        self.dropout = nn.Dropout(p=cfg.output_dropout)
        self.head = get_head(cfg=cfg, n_in=H, n_out=self.output_size)

    def _reset_parameters(self):
        nn.init.orthogonal_(self.weight_ih)
        # hh: identity-block repeated 4 times (standard LSTM initialization)
        eye = torch.eye(self._hidden_size)
        self.weight_hh.data = eye.repeat(1, 4)
        nn.init.zeros_(self.bias)
        if self.cfg.initial_forget_bias is not None:
            # f gate is the 2nd chunk (index H:2H) under (i, f, g, o) ordering
            self.bias.data[self._hidden_size:2 * self._hidden_size] = self.cfg.initial_forget_bias

    def forward(self, data: dict) -> Dict[str, torch.Tensor]:
        x_d, x_s = self.embedding_net(data, concatenate_output=False)
        if x_s is None:
            raise ValueError('FiLMLSTM requires static inputs (x_s or x_one_hot).')

        # Compute gamma, beta ONCE per sample (time-constant modulation)
        gamma, beta = self.film_generator(x_s)  # each [B, 4H]

        B = x_d.shape[1]
        h_t = x_d.new_zeros(B, self._hidden_size)
        c_t = x_d.new_zeros(B, self._hidden_size)
        h_n, c_n = [], []

        input_site = self._film_site == 'input'
        for x_dt in x_d:
            if input_site:
                # FiLM on the input projection only: gamma stays out of the recurrent Jacobian.
                pre_act = gamma * (x_dt @ self.weight_ih) + beta + h_t @ self.weight_hh + self.bias
            else:
                pre_act = x_dt @ self.weight_ih + h_t @ self.weight_hh + self.bias  # [B, 4H]
                pre_act = gamma * pre_act + beta  # FiLM modulation
            i, f, g, o = pre_act.chunk(4, dim=-1)
            i = torch.sigmoid(i)
            f = torch.sigmoid(f)
            g = torch.tanh(g)
            o = torch.sigmoid(o)
            c_t = f * c_t + i * g
            h_t = o * torch.tanh(c_t)
            h_n.append(h_t)
            c_n.append(c_t)

        h_n = torch.stack(h_n, 0).transpose(0, 1)
        c_n = torch.stack(c_n, 0).transpose(0, 1)

        pred = {'h_n': h_n, 'c_n': c_n}
        pred.update(self.head(self.dropout(h_n)))
        return pred
