"""FiLM-LSTM: LSTM with Feature-wise Linear Modulation of gate pre-activations by static attributes.

Reference: Perez et al. 2018, "FiLM: Visual Reasoning with a General Conditioning Layer" (AAAI).
This is a hydrology-specific adaptation: static catchment attributes modulate all 4 LSTM gate
pre-activations via affine (gamma, beta) parameters generated by a small MLP.
"""
from typing import Dict, Tuple

import torch
import torch.nn as nn

from neuralhydrology.modelzoo.basemodel import BaseModel
from neuralhydrology.modelzoo.inputlayer import InputLayer
from neuralhydrology.modelzoo.head import get_head
from neuralhydrology.utils.config import Config


class _FiLMGenerator(nn.Module):
    """MLP that maps static attributes to per-gate (gamma, beta) FiLM parameters.

    Output: (gamma, beta) each of shape [B, 4 * hidden_size], one pair per LSTM gate (i, f, g, o).
    Identity initialization: final-layer weights are zero, biases encode gamma=1, beta=0, so at init
    the FiLM modulation is a no-op (the LSTM behaves as a vanilla LSTM regardless of static input).
    """

    def __init__(self, cfg, static_size: int):
        super().__init__()
        H = cfg.hidden_size
        mid = getattr(cfg, 'film_generator_hidden_size', 64)

        self.mlp_gamma = nn.Sequential(
            nn.Linear(static_size, mid),
            nn.ReLU(),
            nn.Linear(mid, 4 * H),
        )
        self.mlp_beta = nn.Sequential(
            nn.Linear(static_size, mid),
            nn.ReLU(),
            nn.Linear(mid, 4 * H),
        )
        self._identity_init()

    def _identity_init(self):
        # gamma: final weight=0, bias=1 -> gamma ≡ 1 at init (any input yields ones)
        nn.init.zeros_(self.mlp_gamma[-1].weight)
        nn.init.ones_(self.mlp_gamma[-1].bias)
        # beta: final weight=0, bias=0 -> beta ≡ 0 at init
        nn.init.zeros_(self.mlp_beta[-1].weight)
        nn.init.zeros_(self.mlp_beta[-1].bias)

    def forward(self, s: torch.Tensor) -> Tuple[torch.Tensor, torch.Tensor]:
        return self.mlp_gamma(s), self.mlp_beta(s)
