#!/usr/bin/env python3
"""
Filter Caravan basin list to remove basins without valid training data.

Usage (on HPC):
    python src/caravan_global/scripts/filter_basins.py

This script:
1. Reads the original all_basins.txt from data/Caravan/
2. Reads the invalid_basins.txt (basins without data in 1981-2005)
3. Creates valid_basins.txt with only basins that have training data
"""

from pathlib import Path


def main():
    # Paths
    project_root = Path(__file__).parent.parent.parent.parent
    data_dir = project_root / "data" / "Caravan"
    invalid_file = project_root / "src" / "caravan_global" / "data" / "invalid_basins.txt"
    
    all_basins_file = data_dir / "all_basins.txt"
    valid_basins_file = data_dir / "valid_basins.txt"
    
    # Read all basins
    if not all_basins_file.exists():
        print(f"[ERROR] all_basins.txt not found at: {all_basins_file}")
        print("        Make sure you are running this from the project root on HPC")
        return 1
    
    with open(all_basins_file, 'r') as f:
        all_basins = set(line.strip() for line in f if line.strip() and not line.startswith('#'))
    
    print(f"[INFO] Loaded {len(all_basins)} basins from all_basins.txt")
    
    # Read invalid basins
    if not invalid_file.exists():
        print(f"[ERROR] invalid_basins.txt not found at: {invalid_file}")
        return 1
    
    with open(invalid_file, 'r') as f:
        invalid_basins = set(line.strip() for line in f if line.strip() and not line.startswith('#'))
    
    print(f"[INFO] Loaded {len(invalid_basins)} invalid basins")
    
    # Filter
    valid_basins = all_basins - invalid_basins
    removed_count = len(all_basins) - len(valid_basins)
    
    print(f"[INFO] Removed {removed_count} basins without valid training data")
    print(f"[INFO] Remaining valid basins: {len(valid_basins)}")
    
    # Write valid basins (sorted for consistency)
    with open(valid_basins_file, 'w') as f:
        f.write(f"# Valid Caravan basins for training (1981-2005)\n")
        f.write(f"# Generated by filter_basins.py\n")
        f.write(f"# Total: {len(valid_basins)} basins\n")
        for basin in sorted(valid_basins):
            f.write(f"{basin}\n")
    
    print(f"[SUCCESS] Written {len(valid_basins)} valid basins to: {valid_basins_file}")
    
    # Summary by dataset
    datasets = {}
    for basin in valid_basins:
        prefix = basin.split('_')[0]
        datasets[prefix] = datasets.get(prefix, 0) + 1
    
    print("\n[INFO] Valid basins by dataset:")
    for prefix, count in sorted(datasets.items()):
        print(f"       {prefix}: {count}")
    
    return 0


if __name__ == "__main__":
    exit(main())
