name: glofas_haihe_pipeline

subbasins:
  enabled: true
  config: src/haihe_river/configs/glofas/haihe_subbasins.yaml

download:
  enabled: true
  config: src/haihe_river/configs/glofas/haihe_download.yaml

clip:
  enabled: true
  config: src/haihe_river/configs/glofas/haihe_clip.yaml

outlets:
  enabled: true
  config: src/haihe_river/configs/glofas/haihe_outlets.yaml

qc_summary:
  enabled: true
  outputs_dir: data/haihe/glofas/outputs

qc_plots:
  enabled: true
  outputs_dir: data/haihe/glofas/outputs
  subbasin_file: data/haihe/hydrobasins/lev9/haihe_hydrobasins_lev9.gpkg

