#!/usr/bin/env python
"""
Quick Site Setup - Create site template by scanning data directory

Usage:
    # Auto-scan data directory and create template
    python tools/new_site.py --name my_basin --data-dir data/my_basin_hourly
    
    # Specify time split
    python tools/new_site.py --name my_basin --data-dir data/my_basin_hourly \
        --train 2018-01-01:2020-12-31 --val 2021-01-01:2021-06-30 --test 2021-07-01:2022-12-31
"""
import argparse
from pathlib import Path
import yaml
import re


def scan_timeseries(ts_path: Path) -> dict:
    """Scan timeseries folder to detect variables."""
    info = {"rain_cols": [], "flow_col": None, "basins": []}
    
    # Find CSV or NC files
    for f in ts_path.glob("*.csv"):
        info["basins"].append(f.stem)
        # Read header to detect columns
        with open(f, "r", encoding="utf-8") as fp:
            header = fp.readline().strip().split(",")
            for col in header:
                col = col.strip()
                if col.startswith("p_") and col not in info["rain_cols"]:
                    info["rain_cols"].append(col)
                if col in ("qobs", "Q", "discharge", "flow"):
                    info["flow_col"] = col
        break  # Just need one file to get columns
    
    return info


def create_site_template(
    site_name: str,
    data_dir: str,
    train_period: tuple = None,
    val_period: tuple = None,
    test_period: tuple = None,
    output_path: str = None,
) -> Path:
    """Create site configuration template."""
    
    data_path = Path(data_dir).resolve()
    ts_path = data_path / "time_series"
    
    # Scan for variables
    info = {"rain_cols": [], "flow_col": "qobs", "basins": []}
    if ts_path.exists():
        info = scan_timeseries(ts_path)
    
    if not info["rain_cols"]:
        print(f"Warning: No rainfall columns (p_*) found in {ts_path}")
        info["rain_cols"] = ["p_station1"]  # placeholder
    
    if not info["basins"]:
        print(f"Warning: No basin files found in {ts_path}")
        info["basins"] = [site_name]
    
    # Default time periods (adjust as needed)
    train_start, train_end = train_period or ("01/01/2020", "30/06/2021")
    val_start, val_end = val_period or ("01/07/2021", "31/12/2021")
    test_start, test_end = test_period or ("01/01/2022", "31/12/2022")
    
    # Build template
    template = {
        "site_name": site_name,
        "data_dir": str(data_path),
        "run_dir": f"results/{site_name}",
        "train_basin_file": str(data_path / "train_basins.txt"),
        "validation_basin_file": str(data_path / "validation_basins.txt"),
        "test_basin_file": str(data_path / "test_basins.txt"),
        "train_start_date": train_start,
        "train_end_date": train_end,
        "validation_start_date": val_start,
        "validation_end_date": val_end,
        "test_start_date": test_start,
        "test_end_date": test_end,
        "dynamic_inputs": info["rain_cols"],
        "target_variables": [info["flow_col"] or "qobs"],
    }
    
    # Custom normalization for rain/flow (preserve zero)
    custom_norm = {}
    for col in info["rain_cols"]:
        custom_norm[col] = {"centering": "none", "scaling": "std"}
    custom_norm[info["flow_col"] or "qobs"] = {"centering": "none", "scaling": "std"}
    template["custom_normalization"] = custom_norm
    
    # Output
    if output_path:
        out = Path(output_path)
    else:
        out = Path(__file__).parent.parent / "src" / "templates" / f"site_{site_name}.yml"
    
    out.parent.mkdir(parents=True, exist_ok=True)
    
    with open(out, "w", encoding="utf-8") as f:
        f.write(f"# Site Configuration: {site_name}\n")
        f.write(f"# Auto-generated by new_site.py\n")
        f.write(f"# Data scanned from: {data_dir}\n\n")
        yaml.dump(template, f, default_flow_style=False, allow_unicode=True, sort_keys=False)
    
    print(f"Created: {out}")
    
    # Also create basin files if they don't exist
    for basin_file in ["train_basins.txt", "validation_basins.txt", "test_basins.txt"]:
        bf = data_path / basin_file
        if not bf.exists() and info["basins"]:
            with open(bf, "w") as f:
                f.write("\n".join(info["basins"]))
            print(f"Created: {bf}")
    
    return out


def parse_period(s: str) -> tuple:
    """Parse period string like '2020-01-01:2021-12-31' to (start, end) in DD/MM/YYYY."""
    if not s:
        return None
    parts = s.split(":")
    if len(parts) != 2:
        raise ValueError(f"Invalid period format: {s}. Use 'YYYY-MM-DD:YYYY-MM-DD'")
    
    def convert(date_str):
        # Convert YYYY-MM-DD to DD/MM/YYYY
        m = re.match(r"(\d{4})-(\d{2})-(\d{2})", date_str)
        if m:
            return f"{m.group(3)}/{m.group(2)}/{m.group(1)}"
        return date_str
    
    return convert(parts[0]), convert(parts[1])


def main():
    parser = argparse.ArgumentParser(description="Create site template from data directory")
    parser.add_argument("--name", required=True, help="Site name (e.g., my_basin)")
    parser.add_argument("--data-dir", required=True, help="Path to data directory")
    parser.add_argument("--train", help="Train period: YYYY-MM-DD:YYYY-MM-DD")
    parser.add_argument("--val", help="Validation period: YYYY-MM-DD:YYYY-MM-DD")
    parser.add_argument("--test", help="Test period: YYYY-MM-DD:YYYY-MM-DD")
    parser.add_argument("--output", help="Output path (default: src/templates/site_<name>.yml)")
    
    args = parser.parse_args()
    
    create_site_template(
        site_name=args.name,
        data_dir=args.data_dir,
        train_period=parse_period(args.train),
        val_period=parse_period(args.val),
        test_period=parse_period(args.test),
        output_path=args.output,
    )
    
    print(f"\nNext steps:")
    print(f"  1. Review template: src/templates/site_{args.name}.yml")
    print(f"  2. Generate config: python tools/gen_config.py --site {args.name} --type ar --lead 1")
    print(f"  3. Validate: python tools/validate_config.py src/{args.name}/configs/generated/")
    print(f"  4. Train: python tools/run_experiment.py train --config <config.yml>")


if __name__ == "__main__":
    main()






